# Generated by Django 5.2.2 on 2025-06-06 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5)),
                ('nome_completo', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
                ('numero_camisola', models.IntegerField()),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7)),
                ('letra', models.CharField(max_length=1)),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Atleta_Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atleta')),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('equipa_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_em_casa', to='api.equipa')),
                ('equipa_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='api.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Cesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atleta')),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipa')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Atletas_Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atleta')),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipa')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao_Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipa')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
            ],
            options={
                'unique_together': {('jogo', 'equipa')},
            },
        ),
    ]
