# Generated by Django 5.2.2 on 2025-06-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clube_atleta_equipa_atleta_equipa_jogo_cesto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogador',
        ),
    ]
