# Generated by Django 5.2.2 on 2025-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipa',
            name='divisao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
