# Generated by Django 5.2.2 on 2025-06-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipa_divisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesto',
            name='atleta_assistência',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistencias_dadas', to='api.atleta'),
        ),
        migrations.AddField(
            model_name='cesto',
            name='tipo',
            field=models.CharField(choices=[('penalti', 'Penálti'), ('curto', 'Curto'), ('longo', 'Longo'), ('passada', 'Passada')], default='curto', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cesto',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cestos_marcados', to='api.atleta'),
        ),
    ]
