# Generated by Django 5.2.2 on 2025-06-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cesto_atleta_assistência_cesto_tipo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pontuacao_Jogo',
            new_name='Pontuacao_Equipa_Jogo',
        ),
    ]
