# Generated by Django 5.2.2 on 2025-06-08 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_pontuacao_jogo_pontuacao_equipa_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='arbitro_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='arbitro_secundario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='pontuacao_equipa_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='pontuacao_equipa_fora',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('a_decorrer', 'A Decorrer'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tempo_decorrido',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
