# Generated by Django 5.2.2 on 2025-07-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_competicao_epoca_pessoa_remove_atleta_apelido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='numero_telemovel',
        ),
    ]
