# Generated by Django 5.2.2 on 2025-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_pessoa_numero_telemovel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreinadorEquipa',
            new_name='Treinador_Equipa',
        ),
    ]
