# Generated by Django 5.2.2 on 2025-07-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_treinadorequipa_treinador_equipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presidente_Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clube')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.epoca')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.presidente')),
            ],
            options={
                'unique_together': {('presidente', 'clube', 'epoca')},
            },
        ),
    ]
