# Generated by Django 5.2.2 on 2025-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pessoa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/pessoa.png', upload_to='fotos_perfil/'),
        ),
    ]
